# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c143cdb7e3d945ea25d3db2cb0ac476f42d427e0bf9193be55fed2c8a6adba99e4135469e1920ec10855d11e240a14fe4ce9c61530bc065e25039a3460abd4

test:
  secret_key_base: f88945eb5711c2ed184a9a23e7447b13ffd564c0bbd614755d914edc6dc2ecdfa246c7812cc40f8d819ab5140b0ce6c9c9ef663edf5fcbd70f746651608609cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
